name: odontoplan
description: A new Flutter project.


publish_to: 'com.fgm_ti.odontoplan' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Controle de Estado
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+3
  flutter_modular: ^2.0.1
  
  #Autenticação
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  google_sign_in: ^4.5.5
  flutter_twitter_login: ^1.1.0
  #flutter_facebook_auth: "^0.3.0"

  #Persistencia
  hasura_connect: ^2.0.0
  shared_preferences: ^0.5.12+4

  #interface
  #collapsible_sidebar: ^1.0.5
  flutter_signin_button: ^1.1.0
  #font_awesome_flutter: ^8.10.0
  koukicons: ^2.0.3
  path_provider: ^1.6.24

  #relatorios
  pdf: ^1.11.2
  flutter_full_pdf_viewer: ^1.0.6
  open_file: ^3.0.3 

dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: ^2.0.0+1
  mobx_codegen: ^1.1.1+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/dente.png
     - assets/images/default.png
     - assets/images/consultorio.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
